name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install valac
          pip install meson
          pip install ninja
      - name: Build
        run: |
          meson build -Ddebug=true -Db_coverage=true
          ninja -C build
      - name: Run tests
        run: meson test -C build
      - name: Send coverage report
        run: bash <(curl -s https://codecov.io/bash)        